[package]
name = "main"
type = "bin"
authors = ["Kartik Patel"]
compiler_version = ">=0.30.0"

[dependencies]
ecrecover = { path = "../ecrecover-noir" }
mimc = { tag = "v0.1.0", git = "https://github.com/noir-lang/mimc" }